src/stores/tokenDetails.js

resolves #129 
https://github.com/aeternity/aescan/assets/15363559/95e31be3-7a33-49b4-9683-6789370109f4

feat: Order token holders by amount

---

src/components/AccountTransactionsPanel.vue
src/stores/accountDetails.js

resolves #41 
https://github.com/aeternity/aescan/assets/15363559/195cc37a-2d92-403d-bdfd-aa9de07cc223

fix: Account transactions counter bug

---

src/components/TokensTable.vue
src/components/TokensTableCondensed.vue
src/utils/hints/tokensHints.js

feat: Tokens page hints

---

src/components/MarketStats.vue
src/components/StatsPanel.vue
src/stores/blockchainStats.js
src/stores/marketStats.js

resolves #37 
MDW provides slightly different amount, but I guess it's more accurate than AEknow

fix: Remove workaround of total token supply

---

src/components/AppTooltip.vue
src/styles/generic/_animations.css

resolves #275 
https://github.com/aeternity/aescan/assets/15363559/2a456c06-18a4-4217-9201-833aa11808a0

fix: Tooltips bugs

---

README.md

Add aescan.io links to the Readme file.

feat: readme aescan.io link

---

src/components/StateChannelsPanel.vue
src/stores/stateChannels.js

fixes #233 
now went the MDW issue has been resolved https://github.com/aeternity/ae_mdw/issues/1320 (adding closed state channels to listing), the count endpoint will be in sync with the amount in the list.
https://github.com/aeternity/aescan/assets/15363559/933eaef9-64c1-4303-ae2e-a3a3146ccee0

feat: Enable state channel counter 

---

src/stores/recentBlocks.js

resolves #245
https://github.com/aeternity/aescan/assets/15363559/8c30d9ea-4c52-425d-85c6-2a7336d14144

fix: Only up to four transactions can be displayed on the dashboard

---

src/components/OracleEventsPanel.vue
src/stores/oracleDetails.js

Resolves #298 
after this change oracle events are fetched asynchronously also in the client-side
https://github.com/aeternity/aescan/assets/46789227/190e6cf2-e442-4a09-ae21-c5064a4631dc

fix: show oracle details page in CSR when responses endpoint is responding slowly

---

src/components/AppTooltip.vue
src/components/StateChannelsTable.vue
src/components/StateChannelsTableCondensed.vue
src/utils/adapters.js
src/utils/hints/stateChannelsHints.js

resolves #230 
sources used:
https://aeternity.com/state-channels
https://github.com/aeternity/state-channel-demo/blob/develop/TUTORIAL.md
https://github.com/aeternity/state-channel-demo

feat:  State channels Hints

---

src/components/TheFooter.vue

feat: api docs links

---

src/components/ContractCallTransactionsTable.vue
src/components/ContractCallTransactionsTableCondensed.vue

Resolves #276 
This is just a bug fix. Implemented feature related to this task was separated into another issue for better discovery and design: https://github.com/aeternity/aescan/issues/314

fix: empty entry point chip in some contract call transactions

---

src/components/OracleDetailsPanel.vue
src/stores/oracleDetails.js
src/utils/adapters.js

fix: oracle operator value

---

src/components/OracleEventsPanel.vue
src/utils/format.js

fix: oracle events not loading

---

src/components/OracleDetailsPanel.vue

fix: last query height

---

src/stores/accountDetails.js
src/stores/names.js
src/utils/adapters.js

resolves partly #114 
https://github.com/aeternity/aescan/assets/15363559/0cb75776-4396-41ca-8a74-a2b146b1acaa

fix: Move time calculation to MDW

---

src/components/NamesTable.vue
src/utils/adapters.js

fix: name activation price label in dashboard

---

src/components/ContractDetailsPanel.vue
src/components/TheFooter.vue

fixes #249
https://github.com/aeternity/aescan/assets/15363559/ff79a502-97bc-4bb1-9e6b-02e37b71ba4d

fix: Add Middleware link to contract detail

---

src/components/KeyblockSequence.vue
src/styles/generic/_animations.css

resolves #321 
https://github.com/aeternity/aescan/assets/15363559/3bf76b17-e50b-4ff5-af00-e5b1f490b52a

feat: Add currently mined keyblock animation

---

src/components/DashboardTransactionPanel.vue

Resolves #367 
Changes microblock show all link so it navigates the user to microblock details that soon will be containing all transactions

feat: show all microblock transactions link

---

src/components/TheSearchBar.vue
src/stores/keyblockDetails.js

Resolves #368 
I decided to prioritize searching numeric names over keyblocks because there is only a handful of names. Please let me know if that's the correct prioritization  
https://github.com/aeternity/aescan/assets/46789227/46ed8d58-482e-4281-b090-8c7786a3e54c

feat: search by microblock and keyblock ids

---

src/components/MarketStats.vue

Resolves #242 
Testable only or non-mainnet (testnet :sweat_smile: )

feat: network relevant market stats in dashboard

---

src/components/TokenDetailsPanel.vue

fix: Token details layout breaks with no extensions

---

src/utils/hints/accountHints.js
src/utils/hints/contractsHints.js
src/utils/hints/oraclesHints.js

Adding missing page title improvements from #371 CC: @marc0olo

feat: add missing page title hints improvements

---

src/components/HintIcon.vue
src/components/HintTooltip.vue
src/components/OracleEventsQueryPanel.vue
src/components/PageHeader.vue

fix: Low contrast of entity hint icon

---

src/pages/privacy-policy/index.vue
src/pages/terms-of-service/index.vue

fixes #171 
Most of it was resolved in the past, just found small adjustments
visually without changes

fix: Remove temporary styles of Terms & Conditions

---

src/plugins/sentry.js

Fixes #423
N/A
I tested from localhost and some events were recorded on Sentry.

fix: sentry config

---

src/pages/keyblocks/[id].vue

fix: hotfix remove duplicate condition

---

src/app.vue
src/error.vue

feat: Add 500 error page

---

src/components/NamesSwiper.vue
src/components/NamesTable.vue
src/utils/adapters.js

Fixes #432 
A temporary solution for https://github.com/aeternity/ae_mdw/issues/1511. This can be reverted once it's fixed on mdw side.
Tested manually

fix: empty name claims

---

src/stores/status.js

Resolves #439 
Before this fix, we were showing the node version that MDW is using.

feat: display correct Node version

---

src/components/TokenEventsPanel.vue
src/stores/tokenDetails.js

feat: Token events counter

---

src/components/AccountTokensPanel.vue
src/components/AccountTokensTable.vue
src/components/AccountTokensTableCondensed.vue
src/pages/accounts/[id].vue
src/stores/accountDetails.js
src/utils/adapters.js
src/utils/format.js
src/utils/hints/tokensHints.js

Resolves #62 
https://github.com/aeternity/aescan/assets/46789227/ee3a4fc0-3cd8-4223-96b5-1ed53b76aa50

feat: account tokens

---

src/components/ContractDetailsPanel.vue
src/utils/adapters.js

fix: Keyblock height is missing in contract details panel

---

src/components/TransactionCellChannelSnapshotSoloTx.vue

fix: ChannelSnapshotSolo wierd values

---

src/utils/adapters.js

Resolves #461
Issue was caused by imprecise number division

fix: display correct token holder values

---

src/components/StateChannelTransactionsPanel.vue
src/stores/stateChannelDetails.js

feat: display state channel transactions count

---

src/components/NftDetailsPanel.vue
src/components/TokenDetailsPanel.vue
src/pages/accounts/[id].vue
src/pages/contracts/[id].vue
src/pages/keyblocks/[id].vue
src/pages/microblocks/[id].vue
src/pages/nfts/[id].vue
src/pages/oracles/[id].vue
src/pages/state-channels/[id].vue
src/pages/tokens/[id].vue
src/stores/nftDetails.js
src/utils/adapters.js
src/utils/format.js
src/utils/hints/nftHints.js

resolves #145
https://github.com/aeternity/aescan/assets/15363559/6684cef1-d9de-4df8-8f03-b5daf5a64c7e

feat: NFT details panel

---

src/app.vue
src/error.vue
src/errors/EntityDetailsNotFoundError.vue
src/errors/PageNotFoundError.vue
src/errors/SearchNotFoundError.vue
src/pages/accounts/[id].vue
src/pages/contracts/[id].vue
src/pages/contracts/index.vue
src/pages/keyblocks/[id].vue
src/pages/microblocks/[id].vue
src/pages/names/[name].vue
src/pages/names/index.vue
src/pages/nfts/[id].vue
src/pages/nfts/index.vue
src/pages/oracles/[id].vue
src/pages/oracles/index.vue
src/pages/privacy-policy/index.vue
src/pages/search/[id].vue
src/pages/state-channels/[id].vue
src/pages/state-channels/index.vue
src/pages/terms-of-service/index.vue
src/pages/tokens/[id].vue
src/pages/tokens/index.vue
src/pages/transactions/[id].vue
src/pages/transactions/index.vue

Resolves [#414](https://github.com/aeternity/aescan/issues/414)
No visual changes, just refactoring of page titles implementation. They should work just like before

feat: better title handling

---

src/components/AccountDetailsPanel.vue
src/components/AppTab.vue
src/components/AppTabs.vue
src/pages/accounts/[id].vue
src/stores/accountDetails.js

fixes #460
https://github.com/aeternity/aescan/assets/15363559/a3f2ede2-0257-4ede-91d3-d00fd3c6c857

fix: display account details if accounts owns tokens and has never been seen on the network 

---

src/components/DashboardAuctionsPanel.vue
src/components/DashboardAuctionsSwiper.vue
src/components/DashboardAuctionsTable.vue
src/components/DashboardKeyblockPanel.vue
src/components/DashboardMicroblocksPanel.vue
src/components/DashboardNamesPanel.vue
src/components/DashboardNamesSwiper.vue
src/components/DashboardNamesTable.vue
src/components/DashboardPanelHeader.vue
src/components/DashboardStateChannelsPanel.vue
src/components/DashboardTransactionPanel.vue
src/pages/index.vue

resolves #449 
After initial exploration, I discovered that 2 separate components (as it was) it's better solution than just one with multiple parameters and conditions. I just renamed several components to make it less confusing
no visual difference, just renaming

feat: Reuse PanelHeader in AppPanel

---

src/pages/keyblocks/[id].vue

As a hotfix for https://github.com/aeternity/aescan/pull/504
https://github.com/aeternity/aescan/assets/15363559/73aa1063-59de-4369-b246-f42d402184af

fix: keyblock navigation condition

---

src/components/NftsPanel.vue
src/stores/nfts.js

it's sorted by name now
Sorting by creation date is developed but not deployed yet. Followup https://github.com/aeternity/ae_mdw/issues/1572
As a hotfix for https://github.com/aeternity/aescan/pull/504

fix: nfts ordering

---

src/components/ContractDetailsPanel.vue
src/pages/nfts/[id].vue
src/utils/hints/contractsHints.js

resolves #435
https://github.com/aeternity/aescan/assets/15363559/59084af4-fca3-4346-9d1a-31d996e0b869

feat: link to token page for AEX-X classified tokens

---

src/utils/adapters.js

resolves #508 
visually without change

feat: Remove temporary Lexon token constants

---

src/components/AccountTransactionsPanel.vue
src/pages/accounts/[id].vue
src/stores/accountDetails.js

resolves #11
https://github.com/aeternity/aescan/assets/15363559/eb25d377-61a7-4344-abc2-ca1e2af5f94c

feat: Account - Adjust transactions tab display only transactions performed by the account

---

src/components/OraclesPanel.vue
src/components/OraclesSelect.vue
src/components/TransactionsPanel.vue
src/stores/oracles.js
src/utils/constants.js

resolves #160 
https://github.com/aeternity/aescan/assets/15363559/e0f4965e-ffdb-4191-b2ac-c41740fac43b

feat: Implement oracles filtering

---

src/components/NftsPanel.vue
src/stores/nfts.js

feat:  Sort NFTs by creation time

---

src/components/ChartControls.vue
src/components/ContractsChartPanel.vue
src/components/TransactionsChartPanel.vue
src/pages/contracts/index.vue
src/stores/contracts.js

feat: Contract Calls Chart 

---

src/components/TheFooter.vue
src/components/TheHeader.vue

feat: Move survey to the footer 

---

src/components/NamesInAuctionPanel.vue
src/components/OraclesPanel.vue
src/components/TheHeader.vue
src/components/TransactionsPanel.vue
src/components/TransactionsSelect.vue

After the infrastructure upgrade and following fixes, I discovered one more regression
https://github.com/aeternity/aescan/assets/15363559/2bf0832b-c581-4bf9-a580-68c1087fd7ad

fix: fix routing after upgrade

---

src/components/CopyChip.vue
src/components/TokenDetailsPanel.vue

fixes #260
https://github.com/aeternity/aescan/assets/15363559/daa58018-abd7-4275-a1bc-ebb90145bc28

fix: On testnet some tokens have no name at all and clicking on their copy button looks broken

---

src/app.vue
src/layouts/default.vue

Unrelated to issue. Just a quick fix of a visible bug
Before / after

fix: Layout fix

---

package.json
yarn.lock

resolves #583 
https://github.com/aeternity/aescan/assets/15363559/a57c32eb-5873-48a2-9ba1-7d614dace1f2

fix: Search does not work with hashes

---

package.json
src/components/TheSearchBar.vue
yarn.lock

fixes #585 
https://github.com/aeternity/aescan/assets/15363559/bf651298-d838-4709-8119-abd8a3f452a6

fix: search by hashes

---

package.json
src/assets/background.svg
src/components/AppTab.vue
src/components/AppTabs.vue

Also made the background a bit darker which is related to the styles
resolves #552 
https://github.com/aeternity/aescan/assets/15363559/47508ab5-9630-4e3b-acc8-074057f61654

feat: Update tabs design without space between the content

---

package.json
src/components/AppTabs.vue

Resolves #548 
I got inspiration from referenced explorers
https://github.com/aeternity/aescan/assets/15363559/b85e4eae-0fc8-489c-8969-b02102f6329a

fix: Account tabs overflow 

---

package.json
src/components/AccountDetailsPanel.vue
src/components/KeyblockDetailsPanel.vue
src/pages/accounts/[id].vue
src/pages/keyblocks/[id].vue
src/stores/accountDetails.js
src/stores/keyblockDetails.js

fixes #465 
https://github.com/aeternity/aescan/assets/15363559/9c3a7d24-94cb-4cd5-9199-e62c54611d71
I also fixed the user case when going to not existent keyblock.
Previously there was error page. Now there is the explanation panel

fix: Refactor notExistent variables

---

src/styles/utilities/_responsive.css

Found one regression, so I am fixing here.
It is already resolved in https://github.com/aeternity/aescan/pull/549#discussion_r1380489008 so in the case we want to resolve it earlier separately, we can merge this
Before
After

fix: double labels

---

src/components/NamesInAuctionPanel.vue

fixes #612
https://github.com/aeternity/aescan/assets/15363559/1903c6c4-735f-4891-9970-2907cd3e197e

fix: In Auction names pagination bug

---

src/components/AppSelect.vue

fix: Zoom is applied on Transaction page on mobile

---

.github/workflows/ci-code.yml
README.md

feat: upgrade node version to v20

---

src/components/MenuItem.vue
src/components/TheHeader.vue
src/components/TheNavigation.vue
src/styles/generic/_animations.css

resolves #617
https://github.com/aeternity/aescan/assets/15363559/bedb1ed2-43e2-4a69-9d8a-02add4cf1d7c

feat: New menu structure 

---

src/components/TransactionsStatistics.vue
src/stores/transactions.js

feat: transaction trend in the last 24 hours

---

src/pages/transactions/[id].vue

fixes #674
https://github.com/aeternity/aescan/assets/15363559/3b27fa69-79c4-4723-9cad-ceb0116b99f2

fix: When transaction is unavailable the app shows 500 error 

---

src/components/FooterSocials.vue
src/components/TheFooter.vue
src/components/TransactionsChartPanel.vue
src/components/TransactionsStatistics.vue
src/pages/transactions/index.vue

resolve #646
https://github.com/aeternity/aescan/assets/15363559/6730339e-d756-49c2-8275-76c5ad9b8d7e

fix: Improve transaction stats loading

---

src/components/NamePointersCustomPanel.vue

fix: Aligning in Custom pointers to chain names

---

src/components/ContractEventCellBurn.vue

feat: contract events arguments mismatch

---

src/components/AppButton.vue
src/components/AppSelect.vue
src/components/CodeEditor.vue
src/components/PaginationButton.vue
src/components/TheSearchBar.vue
src/styles/elements/_input.css

feat: Update borders color 

---

README.md

Update README urls with the new endpoints.

feat: update readme urls

---

src/components/AppButton.vue
src/components/TransactionTypeTableContractCallTx.vue

resolves #567 
https://github.com/aeternity/aescan/assets/15363559/04707f93-e78d-4736-9216-bb257b27ab97

feat: making call arguments collapsible

---

src/stores/tokens.js

resolves #668
initially, it was fixed here https://github.com/aeternity/aescan/pull/670
There was some back and forth with DEX, so now this is the following fix

feat: revert listed tokens do not appear 

---

src/components/TheFooter.vue
src/components/TheHeader.vue
src/stores/status.js
src/utils/constants.js

feat: Warning about MDW out of sync 

---

src/components/TokenDetailsPanel.vue
src/utils/adapters.js
src/utils/hints/tokensHints.js

resolves #710
https://github.com/aeternity/aescan/assets/15363559/ccdea9a1-0505-42b6-bb27-135c381a2de6

feat: Hide token market cap 

---

src/components/MenuItem.vue
src/components/OracleEventsTableCondensed.vue
src/components/TransactionCellContractCreateTx.vue
src/components/TransactionTypePanel.vue
src/components/TransactionTypeTableContractCreateTx.vue

fixes #706 
I also added 3 more UI small fixes not related to this
https://github.com/aeternity/aescan/assets/15363559/55aedf38-18ad-4f82-98ef-1fd85ee7cfeb

fix: Older button becomes broken in payingfor tx + UI fixes

---

src/pages/terms-of-service/index.vue

feat: smart contract verification terms conditions

---

src/components/ContractsFileUpload.vue

fixes #730
https://github.com/aeternity/aescan/assets/15363559/c5654002-2935-4590-8544-c490184bf93a

fix: Separate direct file selection does not add files

---

package.json
yarn.lock

feat: upgrade sdk to 13.3.2

---

src/components/AccountActivityDataCellContractCallTxEvent.vue

feat: Show ae amount for add_vote Smart Contract call

---

src/stores/transactions.js

fix: Transactions are showing with -0%

---

src/stores/accountDetails.js
src/stores/blockchainStats.js
src/stores/contractDetails.js
src/stores/contracts.js
src/stores/stateChannelDetails.js
src/stores/stateChannels.js
src/stores/transactions.js

feat: migrate transactions count endpoint

---

src/components/KeyblockTable.vue
src/components/KeyblockTableCondensed.vue

fix: BRI Reward zero value is approximated

---

src/components/ContractsFileUpload.vue

https://github.com/aeternity/aescan/pull/724#issuecomment-2057000888
https://github.com/aeternity/aescan/assets/15363559/18e545fa-ee7b-48c7-91fb-26821843ceb3
tried in FF and Chrome

fix: file selection path

---

.github/workflows/ci-e2e.yml

It should be tested with the new tests.

ci: add e2e pipeline

---

src/pages/privacy-policy/index.vue
src/pages/terms-of-service/index.vue

feat: Update terms and conditions entity

---

src/components/TheFooter.vue

resolves #752
displays as expected
https://github.com/aeternity/aescan/assets/15363559/351d6968-7a3d-44be-93ca-909070b7fde2

fix: Sanitize unhandled version values

---

src/components/ContractDetailsPanel.vue
src/components/CopyChip.vue
src/components/NotAvailableLabel.vue
src/components/TokenDetailsPanel.vue
src/components/TokenHoldersTable.vue
src/components/TokenHoldersTableCondensed.vue
src/components/TokensPanel.vue
src/components/TokensTable.vue
src/components/TokensTableCondensed.vue
src/stores/tokenDetails.js
src/stores/tokens.js
src/utils/adapters.js

feat: Display all testnet tokens

---

src/components/ChartsNavigation.vue
src/components/ContractsChartPanel.vue
src/components/TheNavigation.vue
src/components/TransactionsChartPanel.vue
src/pages/charts/contracts.vue
src/pages/charts/keyblocks.vue
src/pages/charts/transactions.vue
src/pages/contracts/index.vue
src/stores/charts.js
src/stores/contracts.js

resolves #715
https://github.com/aeternity/aescan/assets/15363559/3ddcb084-8566-4a87-a495-435b10c3422f

feat: Contract calls chart page

---

src/components/AppButton.vue
src/components/TimeToggleButton.vue

feat: Some time-related labels are not aligned properly on mobile

---

src/components/NftsInventoryTable.vue
src/components/NftsInventoryTableCondensed.vue

https://github.com/aeternity/aescan/assets/15363559/ac158a07-659e-454c-91cf-537267d6ed9f

fix: nft template listing

---

src/error.vue

resolves #795 
https://github.com/aeternity/aescan/assets/15363559/a83017d1-b5e6-4e57-a45c-c29a0488e340

fix: Not found pages break the UI

---

src/utils/constants.js

resolves https://github.com/aeternity/smart-contract-verifier/issues/55

feat: Add ISC license

---

src/stores/contractDetails.js

Smart Contract details is not working.
As a followup @janmichek, an entire page should not stop working if for example a count is not working.

fix: contract calls count

---

src/components/NameDetailsPanel.vue
src/utils/adapters.js
src/utils/format.js
src/utils/hints/namesHints.js

fixes #794
fixes https://github.com/aeternity/aescan/issues/621
Major refactoring has been done. A detailed A/B check with production would be good.
https://github.com/aeternity/aescan/assets/15363559/a7257043-6452-464e-8ee7-47f052888468

fix: Names in auction end date

---

src/stores/charts.js

fix: add keyblock parameter

---

src/components/TheHeader.vue
src/stores/marketStats.js
src/stores/status.js

resolves #95
https://github.com/aeternity/aescan/assets/15363559/153ea9ba-23db-4338-b798-8ac814752d2d

feat: Network unavailability handling

---

src/components/TransactionsStatistics.vue
src/stores/transactions.js

feat: Enable average tx fees panel

---

cypress/e2e/app/aeCoin.cy.js
src/components/AeCoinPanel.vue
src/components/ContractDetailsPanel.vue
src/components/CopyChip.vue
src/components/TheNavigation.vue
src/pages/tokens/AE.vue
src/utils/hints/aeCoinHints.js

resolves #749 
https://github.com/aeternity/aescan/assets/15363559/85a209a8-387e-4055-a69b-8ed9f130b625

feat: Ae coin details

---

src/components/AppDropdown.vue
src/components/MarketsList.vue
src/components/PageHeader.vue
src/pages/tokens/AE.vue

fixes #821
https://github.com/aeternity/aescan/assets/15363559/c76e0f95-a0ad-4640-84ab-fa2f8522b9ed

feat: Trade ae button

---

src/components/AppSelect.vue
src/components/MarketStats.vue
src/components/TrendChip.vue
src/utils/format.js

I noticed several misalignments over app so I fix more small things in this PR without issue
1 Before
1 After
2 Before
2 After
3 Before
https://github.com/aeternity/aescan/assets/15363559/b29146fc-522d-4d27-991d-2892ecf38c65
3 After
https://github.com/aeternity/aescan/assets/15363559/218c791d-5f73-4fa9-9dd8-cb8ebb6c9cf1

fix: UI fixes

---

nuxt.config.ts
src/components/ContractVerifiedTable.vue
src/components/NamePointersSpecialPanel.vue
src/components/OracleEventsQueryPanel.vue
src/components/TokenDetailsPanel.vue
src/components/TokenEventsTableCondensed.vue

feat: UI readability followup

---

src/stores/blockchainStats.js
src/stores/charts.js
src/stores/keyblockDetails.js
src/stores/nftDetails.js
src/stores/oracles.js
src/stores/recentBlocks.js

Charts are broken in production. This should fix it

fix: stats url

---

src/components/NftsTable.vue
src/components/NftsTableCondensed.vue
src/stores/nfts.js
src/utils/adapters.js
src/utils/hints/nftsHints.js

resolves https://github.com/aeternity/aescan/issues/539

feat: Display NFT time value

---

cypress/e2e/app/homepage.cy.js
cypress/support/e2e.ts
src/components/ContractEventCellDeposit.vue
src/components/ContractEventCellWithdrawal.vue
src/components/PriceLabel.vue
src/utils/format.js

fix: Fixes 0.16.0

---

src/stores/tokenDetails.js

fix: fixes 0.16.0 pt 2

---

src/components/TransactionGeneralPanel.vue
src/components/TransactionTypeTableContractCallTx.vue
src/components/TransactionTypeTableContractCreateTx.vue
src/components/TransactionTypeTableGAAttachTx.vue

resolves https://github.com/aeternity/aescan/issues/941

fix: Remove AE label from gas value 

---

.github/workflows/ci-code.yml
.github/workflows/dev-pipeline-mainnet.yml
.github/workflows/dev-pipeline-testnet.yml
.github/workflows/prd-pipeline-mainnet.yml
.github/workflows/prd-pipeline-testnet.yml
.github/workflows/release-create.yml
.github/workflows/stg-pipeline-mainnet.yml
.github/workflows/stg-pipeline-testnet.yml

ci: update checkout action to v3

---

src/components/OracleEventsQueryPanel.vue
src/utils/format.js

fixes https://github.com/aeternity/aescan/issues/947

fix: Add N/A label for no query and response even

---

src/components/AppLink.vue

fixes #167 
Only internal refactoring, there should not be any effect visible to user

feat: Use nuxt-link

---

cypress.config.ts
cypress/e2e/app/accountDetail.cy.js
cypress/e2e/app/homepage.cy.js
cypress/e2e/app/termsOfService.cy.js

feat: e2e testing improvements

---

src/components/ContractEventCellAllowance.vue
src/components/ContractEventCellBurn.vue
src/components/ContractEventCellMint.vue

fixes #967
https://pr-969-aescan.stg.service.aepps.com/contracts/ct_2Xdym95f2i998W9Zoh1NgAB7pVuQ34ztEsema7u4XwSoq5VKUJ

fix: sanitize contract events

---

cypress/e2e/app/oracles.cy.js
src/stores/accountDetails.js
src/stores/nameDetails.js
src/stores/nftDetails.js

fix: code cleanup

---

cypress.config.ts
cypress/e2e/app/nameDetail.cy.js
cypress/e2e/app/search.cy.js
src/stores/accountDetails.js

feat: improve e2e testing - search

---

cypress/e2e/app/charts.cy.js
cypress/e2e/app/contractVerification.cy.js
src/components/ContractVerificationForm.vue
src/components/DifficultyChartPanel.vue
src/components/NamesChartPanel.vue
src/components/TransactionsChartPanel.vue

feat: improve e2e testing - charts

---

src/app.vue

feat: Add entity id to page title

---

cypress/e2e/app/charts.cy.js
src/components/ChartsNavigation.vue
src/components/ContractsChartPanel.vue
src/components/DifficultyChartPanel.vue
src/components/HashrateChartPanel.vue
src/components/KeyblocksChartPanel.vue
src/components/NamesChartPanel.vue
src/components/TheNavigation.vue
src/components/TransactionsChartPanel.vue
src/pages/charts/difficulty.vue
src/pages/charts/hashrate.vue
src/stores/charts.js

fixes #694 
@Liubov-crypto to check all charts in app

feat: hashrate chart

---

src/app.vue

small fix without issue
BEFORE
AFTER

fix: page title printing

---

src/components/AccountsChartPanel.vue
src/components/ContractsChartPanel.vue
src/components/DifficultyChartPanel.vue
src/components/HashrateChartPanel.vue
src/components/KeyblocksChartPanel.vue
src/components/NamesChartPanel.vue
src/components/TransactionsChartPanel.vue
src/pages/accounts/index.vue
src/pages/charts/transactions.vue
src/pages/contracts/index.vue
src/pages/names/index.vue
src/pages/transactions/index.vue

fix: defaul chart options

---

cypress.config.ts

fix: e2e randomly failing 

---

src/components/MicroblockDetailsPanel.vue
src/utils/hints/microblocksHints.js

feat: Show Block gas limit 2

---

.github/workflows/stg-pipeline-mainnet.yml
.github/workflows/stg-pipeline-testnet.yml

ci: fix gh action undeploy step triggers

---

cypress.config.ts
src/components/BlockTimeCell.vue
src/components/OracleDetailsPanel.vue
src/components/OracleEventsPanel.vue
src/components/OraclesPanel.vue
src/components/TimestampLabel.vue
src/composables/blockchainStats.js
src/composables/oracleDetails.js
src/composables/oracles.js
src/composables/useAxios.js
src/pages/oracles/[id].vue
src/server/api/oracles/[id].js
src/server/api/oracles/count.js
src/server/api/oracles/events.js
src/server/api/oracles/index.js
src/utils/adapters.js
src/utils/format.js

feat: server handlers oracles

---

Dockerfile

feat: multi stage Docker build

---

src/assets/styles/settings/_variables.css
src/components/AccountDetailsPanel.vue
src/components/AeCoinPanel.vue
src/components/ContractDetailsPanel.vue
src/components/KeyblockDetailsPanel.vue
src/components/MicroblockDetailsPanel.vue
src/components/NameDetailsPanel.vue
src/components/NftDetailsPanel.vue
src/components/OracleDetailsPanel.vue
src/components/StateChannelDetailsPanel.vue
src/components/TimestampLabel.vue
src/components/TokenDetailsPanel.vue
src/components/TransactionGeneralPanel.vue
src/layouts/default.vue

fixes https://github.com/aeternity/aescan/issues/1018

feat: mobile view details panel 2

---

src/components/BlockTimeCell.vue
src/components/OracleDetailsPanel.vue
src/components/OracleEventsPanel.vue
src/components/OraclesPanel.vue
src/components/TimestampLabel.vue
src/composables/blockchainStats.js
src/composables/oracleDetails.js
src/composables/oracles.js
src/composables/useAxios.js
src/pages/oracles/[id].vue
src/server/api/oracles/[id].js
src/server/api/oracles/count.js
src/server/api/oracles/events.js
src/server/api/oracles/index.js
src/utils/adapters.js
src/utils/format.js

feat: server handlers oracles 2, 3

---

src/components/TheSearchBar.vue
src/composables/keyblockDetails.js
src/composables/keyblocks.js
src/composables/search.js
src/errors/EntityDetailsNotFoundError.vue
src/server/api/keyblocks/[id].js
src/server/api/keyblocks/index.js
src/server/api/keyblocks/microblocks.js
src/utils/adapters.js

feat: Server handlers keyblocks 6

---

src/components/KeyblockMicroblocksPanel.vue
src/composables/keyblockDetails.js
src/composables/search.js
src/server/api/keyblocks/[id].js
src/server/api/keyblocks/index.js
src/server/api/keyblocks/microblocks.js
src/server/api/oracles/[id].js
src/server/api/oracles/count.js
src/server/api/oracles/events.js
src/server/api/oracles/index.js
src/server/api/search/[keyblockId].js
src/server/api/search/names.js
src/server/api/search/nfts.js
src/server/api/search/tokens.js
src/server/utils/urlBuilder.js

feat: Server handlers search 2

---

cypress/e2e/app/transactions.cy.js

fix: transaction test

---

src/composables/charts.js
src/composables/topAccounts.js
src/utils/constants.js

feat: Increase statistics limit

---

src/components/DashboardKeyblockPanel.vue
src/components/DashboardKeyblockTableCondensed.vue
src/components/TimestampLabel.vue
src/components/TokenSymbolIcon.vue
src/composables/dex.js

fix: UI fixes 5

---

src/components/StateChannelTransactionsPanel.vue
src/composables/stateChannelDetails.js
src/composables/stateChannels.js
src/pages/keyblocks/[id].vue
src/pages/state-channels/[id].vue
src/server/api/channels/[id].js
src/server/api/channels/count.js
src/server/api/channels/index.js
src/server/api/channels/transactions.js

feat: Server handlers state channels 2

---

src/components/TransactionTypeTableContractCallTx.vue

fixes #849
https://pr-1111-aescan.stg.service.aepps.com/transactions/th_2SWUUuQZ5YS1G1ZxFQ41Dny1enTA79D98reojKm9qKB5vv1Kx1

fix: Confusing scientific notation for numbers

---

src/components/NftInventoryPanel.vue
src/components/NftOwnersPanel.vue
src/components/NftTemplatesOwnersPanel.vue
src/components/NftTransfersPanel.vue
src/components/NftsPanel.vue
src/composables/nftDetails.js
src/composables/nfts.js
src/server/api/nfts/[id].js
src/server/api/nfts/index.js
src/server/api/nfts/inventory.js
src/server/api/nfts/owners.js
src/server/api/nfts/transfers.js

resolves https://github.com/aeternity/aescan/issues/517
partly resolves #909

feat:  server handlers nfts

---

src/components/DashboardKeyblockPanel.vue

fix: text content change

---

src/components/AeCoinMarketsTable.vue
src/components/MarketsList.vue
src/server/api/tokens/ae.js
src/utils/constants.js

fix: remove delisted coinstore from app

---

src/components/StateChannelsPanel.vue

fixes: https://github.com/aeternity/aescan/issues/1132
https://github.com/user-attachments/assets/ff6881ea-3f86-430b-b61b-79b28d48b480

fix: state channels pagination pagination

---

CHANGELOG.md
src/components/DoughnutChart.vue
src/components/MinersTable.vue
src/components/MiningStatisticsGrid.vue
src/server/api/mining/miners.js
src/server/api/mining/statistics.js

fix: Mining pool dashboard fixes
