aeternity/aescan

.github/workflows/release-post.yml

Resolves #250 
The CI workflow that is responsible for creating a port pull request in case of conflicts was configured incorrectly and causing failure. Now it's fixed. After merging I will try to trigger it manually.
Tested on a forked repo

fix: release porting ci

---

.github/workflows/release-please.yml

Resolves #280 
This fix prevents release-please action from releasing a new version without any new changes. Can be tested after merging upon next "patch version" release
Tested on forked repo.
Without new commits:
With new commits:

fix: workflow for releasing patch version of the app

---

src/components/HintIcon.vue
src/components/HintTooltip.vue
src/components/StatsTile.vue

resolves #84 
https://github.com/aeternity/aescan/assets/15363559/81db6d2c-d2ac-452e-85d5-03788d39e335

feat: Improve hint icon alignment across the application

---

src/stores/nameDetails.js
src/utils/adapters.js

Resolves #267 
The problem was the lack of support for internal contract call events which have a different payload.

fix: support for internal call event in name actions

---

src/components/AppTabs.vue
src/pages/names/index.vue

Resolves #278 
Fixes regression introduced when rewriting this area to composition API. It also improves the interaction with name history so that the `/names` page stays in the browser history only with the included query parameter (no duplicate).
https://github.com/aeternity/aescan/assets/46789227/3fd4aab0-42fb-4225-9756-7a7a7db388ce

fix: switching names type tabs interacting with browser history

---

README.md
src/components/OracleEventsPanel.vue

Resolves #345 
This change reimplements data-failed-state in oracle events panel. The issue described in the original task was caused by recreating the paginated-content component every time there is data fetching which was resetting the page index back to 1. 
https://github.com/aeternity/aescan/assets/46789227/615530d1-5607-403f-986a-89f1de1e611f

fix: DataFailedState component does not work with pagination

---

src/components/TransactionCellOracleRespondTx.vue

This pr has been forgotten to merge in previous MVP private repo, so just moving it here
Before 
After

fix: Oracle response of OracleRespondTx transactions is not displayed correctly

---

src/components/LoaderIndicator.vue
src/components/LoaderPanel.vue
src/components/PaginatedContent.vue
src/composables/useLoading.js
src/pages/accounts/[id].vue
src/pages/contracts/[id].vue
src/pages/contracts/index.vue
src/pages/keyblocks/[id].vue
src/pages/microblocks/[id].vue
src/pages/names/[name].vue
src/pages/names/index.vue
src/pages/oracles/[id].vue
src/pages/oracles/index.vue
src/pages/state-channels/[id].vue
src/pages/state-channels/index.vue
src/pages/tokens/[id].vue
src/pages/tokens/index.vue
src/pages/transactions/[id].vue
src/pages/transactions/index.vue

fixes #391 
https://github.com/aeternity/aescan/assets/15363559/ebaaa15e-aa13-4914-944c-35756209e1b3

feat: Loading indicator for panels  2

---

src/components/AccountDetailsPanel.vue
src/components/AccountTokensTable.vue
src/components/AccountTokensTableCondensed.vue
src/components/TokenDetailsPanel.vue
src/stores/accountDetails.js
src/stores/dex.js
src/stores/tokenDetails.js
src/utils/adapters.js
src/utils/constants.js
src/utils/format.js

Resolves #481 
Fixes unreliable token prices and marketcaps  in token details page and account details -> tokens
Examples:
account: ak_aeksJqKvh1HD4rSACRjSUGgVe4nEywq6C9VK6VYXwUMezePyH
tokens: ct_KeTvHnhU85vuuQMMZocaiYkPL9tkoavDRT3Jsy47LK2YqLHYb, ct_BwJcRRa7jTAvkpzc2D16tJzHMGCJurtJMUBtyyfGi2QjPuMVv

fix: token prices and meaningful number formatting

---

src/components/MicroblockTransactionsPanel.vue
src/components/TransactionsSelect.vue

resolves #398 
I was testing on mh_QzEw8iHQoZN5wNYNV2ZhXDXnHv1juNrazX8y2Vw9Nh5HFgLqg but better find another one .)
https://github.com/aeternity/aescan/assets/15363559/ecf3a56c-9001-45e5-8837-38c18cbc2d91

feat: add microblocks transactions filtering

---

src/components/KeyblockMicroblocksTableCondensed.vue

The tx counter for the microbloks in a keyblock was not showing on the condensed keyblock view due to wrong property given.
| Before | After |
| ------ | ----- |
|  ![Screenshot from 2023-11-07 08-56-24](https://github.com/aeternity/aescan/assets/13139371/e8bd184a-a102-42ed-b205-9056ad565dd8)  |  ![Screenshot from 2023-11-07 08-56-32](https://github.com/aeternity/aescan/assets/13139371/df8d6118-42a3-4c43-a866-2dc14ee07e2c)  |

fix: microblocks tx counter at keyblock condensed

---

src/pages/transactions/[id].vue
src/stores/recentBlocks.js
src/stores/webSocket.js

resolves #543
https://github.com/aeternity/aescan/assets/15363559/e7d7268c-9942-43cd-8e26-ba99c9869a9b

feat: Live update transaction details

---

package.json
src/components/AccountDetailsPanel.vue
src/components/KeyblockDetailsPanel.vue
src/components/MicroblockDetailsPanel.vue
src/components/NftsDetailsPanel.vue
src/components/OracleDetailsPanel.vue
src/components/StateChannelDetailsPanel.vue
src/components/TransactionGeneralPanel.vue
src/components/TransactionTypePanel.vue
src/components/TransactionTypeTableSpendTx.vue
src/components/ValueHashEllipsed.vue
src/utils/constants.js
src/utils/format.js

resolves #451 
known addresses are listed here https://github.com/aeternity/aescan/pull/573/files#diff-bd2e652035adaf33b6125f14a823cf76feae0c1c1a592e9a6c14a14951a52a28R96
https://github.com/aeternity/aescan/assets/15363559/372f2133-1736-483c-a6aa-493ae1a3034d

feat: translate known addresses

---

package.json
src/components/AccountDetailsPanel.vue
src/stores/accountDetails.js
src/utils/hints/accountHints.js

Initially I grabbed the issue https://github.com/aeternity/aescan/issues/553
Found out that 
1) Such an endpoint does not exist (requested here https://github.com/aeternity/ae_mdw/issues/1629)
2) There was a wrong attempt to get names count, that was not even implemented (dead code) SO at least I removed the dead code
Without any visual change. Should work the same

fix: remove unused attempt for account names counter

---

src/components/LineChart.vue
src/components/MicroblockTransactionsPanel.vue
src/components/NamesChartPanel.vue
src/pages/names/index.vue
src/stores/names.js
src/stores/oracleDetails.js

feat: Names charts

---

src/components/AccountActivityCell.vue
src/components/AccountActivityDataCell.vue
src/components/AccountActivityDataCellAex141TransferEvent.vue
src/components/AccountActivityTypeCell.vue

fixes #628
related https://github.com/aeternity/aescan/issues/362
https://github.com/aeternity/aescan/assets/15363559/f326a9a7-446f-4e5c-b087-b984d195faa9

fix:  If user look at the activity of the selected account, then in the third step the view will break

---

src/components/AccountActivityDataCellInternalContractCallEvent.vue

feat: internal Chain.spend values

---

src/components/AccountActivityDataCellNameClaimTxEvent.vue
src/components/NameHistoryDataCellNameClaimEvent.vue
src/components/TransactionCellNameClaimTx.vue
src/components/TransactionTypeTableNameClaimTx.vue

resolves #727 
Not sure why it stopped working now. I believe all was working before, there has not been any change in files for a year.
https://github.com/aeternity/aescan/assets/15363559/2f936ea6-ab6d-4947-a8a6-89f4f9d3b063

fix: Name fee is empty

---

.github/workflows/ci-code.yml
.github/workflows/ci-pr.yml
.github/workflows/dev-pipeline-mainnet.yml
.github/workflows/dev-pipeline-testnet.yml
.github/workflows/prd-pipeline-mainnet.yml
.github/workflows/prd-pipeline-testnet.yml
.github/workflows/stg-pipeline-mainnet.yml
.github/workflows/stg-pipeline-testnet.yml

PR without an issue just quickly shortening the names for better orientation. Does not have effect the functionality
Before
After

feat: change action naming

---

src/components/SearchNamesTable.vue
src/components/SearchNamesTableCondensed.vue
src/stores/search.js
src/utils/adapters.js
src/utils/format.js

feat: Names search case insensitive

---

src/app.vue
src/components/AeCoinPanel.vue
src/components/MarketStats.vue
src/components/TransactionsStatistics.vue
src/components/TrendChip.vue

I encounter a bug in develop about trend signing. It was incorrect and inconsistent.
Here I centralized the logic of trend chip used multiple times over app to the reusable component
Before
after

fix: Trend sign fix

---

src/components/KeyblockDetailsPanel.vue

fix: Show accounts created in genesis block

---

src/components/NftsPanel.vue
src/components/TokenDetailsPanel.vue
src/components/TokensPanel.vue
src/pages/contracts/[id].vue
src/stores/accountDetails.js
src/stores/contractDetails.js
src/stores/nfts.js
src/stores/search.js
src/stores/tokenDetails.js
src/stores/tokens.js

related https://github.com/aeternity/aescan/issues/690
I tried to migrate all of the rest v2 endpoints.
These were ready to migrate.
The ones that are still not migrated produced some error, which I reported to MDW
Internal change, no change should be visible from UI compared to develop
Parts that needs to be tested
NFTs
Tokens
Token Detail
contract Detail
search

feat: Migrate to v3 endpoints another part

---

cypress/e2e/app/topAccounts.js
src/components/TheNavigation.vue
src/components/TopAccountsPanel.vue
src/components/TopAccountsTable.vue
src/components/TopAccountsTableCondensed.vue
src/pages/accounts/index.vue
src/pages/top-accounts/index.vue
src/stores/topAccounts.js
src/utils/adapters.js
src/utils/hints/topAccountsHints.js

resolves #616 
- The endpoint responds with top 200 accounts. Cannot be limited to 100. I think we can proceed with that https://mainnet.aeternity.io/mdw/v3/wealth?limit=100
https://github.com/aeternity/aescan/assets/15363559/2087fa57-f8d8-4090-91ac-2f3c69223780

feat: Top accounts

---

src/components/TokenEventsPanel.vue
src/stores/accountDetails.js
src/stores/names.js
src/stores/nftDetails.js
src/stores/tokenDetails.js

another part of migration endoints
when testing, focus on account tokens listing and token events counter, nft detail
partly resolves https://github.com/aeternity/aescan/issues/690
Should work without any change

feat: Migrate to v3 part

---

Dockerfile

Port 8080 has to be exposed, instead of 80, because the process is started by a non-root user which can't expose ports like 80.

fix: expose port 8080 in Docker
